-- drop tables if they exist
DROP TABLE IF EXISTS public.cc_audit_document_checkpoints CASCADE;
DROP TABLE IF EXISTS public.cc_audit_document_rating_options CASCADE;
DROP TABLE IF EXISTS public.cc_audit_documents CASCADE;
DROP TABLE IF EXISTS public.cc_clients CASCADE;
DROP TABLE IF EXISTS public.cc_stock_products CASCADE;
DROP TABLE IF EXISTS public.cc_stock_clients CASCADE;
DROP TABLE IF EXISTS public.cc_stock_providers CASCADE;
DROP TABLE IF EXISTS public.cc_stock_product_categories CASCADE;
DROP TABLE IF EXISTS public.cc_stock_product_measure_units CASCADE;
DROP TABLE IF EXISTS public.cc_audit_document_template_checkpoints CASCADE;
DROP TABLE IF EXISTS public.cc_audit_document_template_checkpoint_types CASCADE;
DROP TABLE IF EXISTS public.cc_audit_document_template_sections CASCADE;
DROP TABLE IF EXISTS public.cc_audit_document_templates CASCADE;
DROP TABLE IF EXISTS public.cc_states CASCADE;
DROP TABLE IF EXISTS public.cc_settings CASCADE;
DROP TABLE IF EXISTS public.cc_users CASCADE;
DROP TABLE IF EXISTS public.cc_user_businesses CASCADE;
DROP TABLE IF EXISTS public.cc_plugins CASCADE;
DROP TABLE IF EXISTS public.cc_user_roles CASCADE;
DROP TABLE IF EXISTS public.cc_user_genders CASCADE;
DROP TABLE IF EXISTS public.cc_countries CASCADE;
DROP TABLE IF EXISTS public.cc_payment_methods CASCADE;
DROP TABLE IF EXISTS public.cc_currency_types CASCADE;

-- create tables
create table public.cc_currency_types (
    id serial primary key,
    abbreviation varchar(10) not null,
    name varchar(100) not null,
    unique (abbreviation)
);
create table public.cc_payment_methods (
    id bigint generated by default as identity,
    name text null,
    constraint cc_payment_methods_pkey primary key (id)
) tablespace pg_default;
create table public.cc_countries (
    id bigint generated by default as identity,
    abbreviation varchar(10) not null,
    name varchar(100) not null,
    unique (abbreviation),
    constraint cc_countries_pkey primary key (id)
);
create table public.cc_user_genders (
    id bigint generated by default as identity,
    abbreviation varchar(10) not null,
    name varchar(100) not null,
    unique (abbreviation),
    constraint cc_user_genders_pkey primary key (id)
);
create table public.cc_user_roles (
    id bigint generated by default as identity,
    name text null,
    constraint cc_user_role_pkey primary key (id)
);

create table public.cc_plugins (
    id bigint generated by default as identity not null,
    name text not null,
    description text null
) TABLESPACE pg_default;

create table public.cc_user_businesses (
  id bigint generated by default as identity not null,
  name text null,
  enabled_plugins jsonb not null default '[]'::jsonb,
  constraint cc_user_businesses_pkey primary key (id)
) TABLESPACE pg_default;

create table public.cc_users (
    id bigint generated by default as identity,
    first_name text null,
    last_name text null,
    phone text null,
    email text null,
    username text null,
    password text null,
    is_root boolean null default false,
    cc_user_role_id bigint null,
    is_active boolean null default false,
    is_banned boolean null default false,
    is_blocked boolean null default false,
    token text null,
    dni_ssn text null,
    cc_user_gender_id bigint null default '4'::bigint,
    cc_country_id bigint null,
    birthdate date null,
    cc_user_business_id bigint null default 1,
    created_by_user_id bigint null,
    constraint cc_users_pkey primary key (id),
    constraint cc_users_email_key unique (email),
    constraint platform_users_created_by_user_id_fkey foreign key (created_by_user_id) references cc_users (id) on update cascade on delete
    set null,
        constraint cc_users_cc_country_id_fkey foreign key (cc_country_id) references countries (id) on update cascade on delete
    set null,
        constraint cc_users_cc_user_gender_id_fkey foreign key (cc_user_gender_id) references cc_user_genders (id) on update cascade on delete
    set null,
        constraint cc_users_cc_user_role_id_fkey foreign key (cc_user_role_id) references cc_user_roles (id) on update cascade on delete
    set null,
        constraint cc_users_cc_user_business_id_fkey foreign key (cc_user_business_id) references cc_user_businesses (id) on update cascade on delete
    set null
) tablespace pg_default;
create table public.cc_settings (
    id bigint generated by default as identity,
    contact_number varchar(15) null,
    developer_name varchar(100) not null,
    developer_contact_email varchar(100) null,
    constraint cc_settings_pkey primary key (id),
    constraint cc_settings_name_key unique (developer_name)
) tablespace pg_default;
create table public.cc_states (
    id bigint generated by default as identity,
    name text null,
    constraint cc_states_pkey primary key (id)
) tablespace pg_default;

create table
  public.cc_audit_document_templates (
    id bigint generated by default as identity not null,
    title text not null,
    description text null,
    cc_user_business_id bigint null,
    constraint cc_audit_document_templates_pkey primary key (id),
    constraint cc_audit_document_templates_cc_user_business_id_fkey foreign key (cc_user_business_id) references cc_user_businesses (id)
  ) tablespace pg_default;

create table
  public.cc_audit_document_template_checkpoint_types (
    id bigint generated by default as identity not null,
    name text not null,
    description text null,
    constraint cc_audit_document_template_checkpoint_types_pkey primary key (id)
  ) tablespace pg_default;

create table 
  public.cc_audit_document_template_sections (
    id bigint generated by default as identity not null,
    name text not null,
    description text null,
    cc_audit_document_template_id bigint not null,
    constraint cc_audit_document_template_checkpoint_pkey primary key (id),
    constraint cc_audit_document_template_c_cc_audit_document_template_i_fkey1 foreign KEY (cc_audit_document_template_id) references cc_audit_document_templates (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table 
  public.cc_audit_document_template_checkpoints (
    id bigint generated by default as identity not null,
    title text not null,
    description text null,
    cc_audit_document_template_id bigint not null,
    cc_audit_document_template_checkpoint_type_id bigint not null,
    cc_audit_document_template_section_id bigint not null,
    constraint cc_audit_document_template_checkpoints_pkey primary key (id),
    constraint cc_audit_document_template_ch_cc_audit_document_template_c_fkey foreign KEY (cc_audit_document_template_checkpoint_type_id) references cc_audit_document_template_checkpoint_types (id) on update CASCADE on delete CASCADE,
    constraint cc_audit_document_template_ch_cc_audit_document_template_i_fkey foreign KEY (cc_audit_document_template_id) references cc_audit_document_templates (id) on update CASCADE on delete CASCADE,
    constraint cc_audit_document_template_ch_cc_audit_document_template_s_fkey foreign KEY (cc_audit_document_template_section_id) references cc_audit_document_template_sections (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.cc_clients (
    id bigint generated by default as identity not null,
    name text not null,
    description text null,
    created_by_cc_user_business_id bigint not null,
    constraint cc_clients_pkey primary key (id),
    constraint cc_clients_created_by_cc_user_business_id_fkey foreign key (created_by_cc_user_business_id) references cc_user_businesses (id) on update cascade on delete cascade,
    constraint unique_name_per_business unique (name, created_by_cc_user_business_id) 
) tablespace pg_default;


create table public.cc_stock_clients (
    id bigint generated by default as identity not null,
    name text not null,
    description text null,
    created_by_cc_user_business_id bigint not null,
    constraint cc_stock_clients_pkey PRIMARY key (id),
    constraint cc_clients_created_by_cc_user_business_id_fkey 
        foreign key (created_by_cc_user_business_id) 
        references cc_user_businesses (id) 
        on update cascade on delete cascade,
    constraint unique_name_per_business_new 
        UNIQUE (name, created_by_cc_user_business_id)
) tablespace pg_default;

create table
  public.cc_audit_documents (
    id bigint generated by default as identity not null,
    cc_audit_document_template_id bigint not null,
    date date null,
    total_not_verified_points bigint null default '0'::bigint,
    total_implemented_points bigint null default '0'::bigint,
    total_partially_implemented_points bigint null default '0'::bigint,
    total_not_implemented_points bigint null default '0'::bigint,
    created_by_cc_user_id bigint null,
    cc_client_id bigint not null,
    cc_state_id bigint null default '1'::bigint,
    final_comments text null,
    total_excluded_points bigint null default '0'::bigint,
    accessible_users jsonb null default '[]'::jsonb,
    constraint cc_audit_documents_pkey primary key (id),
    constraint cc_audit_documents_cc_audit_document_template_i_fkey foreign key (cc_audit_document_template_id) references cc_audit_document_templates (id) on update cascade on delete cascade,
    constraint cc_audit_documents_cc_client_id_fkey foreign key (cc_client_id) references cc_clients (id) on update cascade on delete cascade,
    constraint cc_audit_documents_cc_state_id_fkey foreign key (cc_state_id) references cc_states (id) on update cascade on delete cascade,
    constraint cc_audit_documents_created_by_cc_user_id_fkey foreign key (created_by_cc_user_id) references cc_users (id) on update cascade on delete set null
  ) tablespace pg_default;

create table
  public.cc_audit_document_rating_options (
    id bigint generated by default as identity not null,
    name text null,
    constraint cc_audit_document_rating_options_pkey primary key (id)
  ) tablespace pg_default;

create table public.cc_audit_document_checkpoints (
  id bigint generated by default as identity not null,
  cc_audit_document_template_checkpoint_id bigint not null,
  has_image_preview_1 boolean null default false,
  image_preview_link_1 text null,
  has_image_preview_2 boolean null default false,
  image_preview_link_2 text null,
  has_image_preview_3 boolean null default false,
  image_preview_link_3 text null,
  has_image_preview_4 boolean null default false,
  image_preview_link_4 text null,
  has_image_preview_5 boolean null default false,
  image_preview_link_5 text null,
  cc_audit_document_rating_option_id bigint not null,
  cc_audit_document_id bigint null,
  description text null,
  constraint cc_audit_document_checkpoints_pkey primary key (id),
  constraint cc_audit_document_checkpoints_cc_audit_document_id_fkey foreign KEY (cc_audit_document_id) references cc_audit_documents (id) on update CASCADE on delete CASCADE,
  constraint cc_audit_document_checkpoints_cc_audit_document_rating_opt_fkey foreign KEY (cc_audit_document_rating_option_id) references cc_audit_document_rating_options (id) on update CASCADE on delete CASCADE,
  constraint cc_audit_document_checkpoints_cc_audit_document_template_c_fkey foreign KEY (cc_audit_document_template_checkpoint_id) references cc_audit_document_template_checkpoints (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;


create table public.cc_stock_product_categories (
  id bigint generated by default as identity not null,
  name character varying(100) not null,
  description text null,
  cc_user_business_id bigint null,
  constraint cc_stock_product_categories_pkey primary key (id),
  constraint cc_stock_product_categories_name_key unique (name),
  constraint cc_stock_product_categories_cc_user_business_id_fkey foreign KEY (cc_user_business_id) references cc_user_businesses (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.cc_stock_product_measure_units (
  id bigint generated by default as identity not null,
  name character varying(100) not null,
  description text null,
  cc_user_business_id bigint null,
  constraint cc_stock_product_measure_units_pkey primary key (id),
  constraint cc_stock_product_measure_units_name_key unique (name),
  constraint cc_stock_product_measure_units_cc_user_business_id_fkey foreign KEY (cc_user_business_id) references cc_user_businesses (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.cc_stock_providers (
    id bigint generated by default as identity not null,
    name text not null,
    description text null,
    created_by_cc_user_business_id bigint not null,
    constraint cc_stock_providers_pkey primary key (id),
    constraint cc_providers_created_by_cc_user_business_id_fkey 
        foreign key (created_by_cc_user_business_id) 
        references cc_user_businesses (id) 
        on update cascade on delete cascade,
    constraint unique_name_per_business_new_renamed 
        UNIQUE (name, created_by_cc_user_business_id)
) tablespace pg_default;

create table public.cc_stock_products (
  id bigint generated by default as identity not null,
  name character varying(100) not null,
  description text null,
  has_image boolean not null default false,
  image_path text null,
  cc_stock_product_category_id integer not null,
  price numeric(10, 2) not null,
  cc_stock_product_measure_unit_id integer not null,
  quantity integer not null,
  has_bar_code boolean not null default false,
  bar_code text null,
  created_at timestamp without time zone null default CURRENT_TIMESTAMP,
  cc_user_business_id bigint null,
  cc_stock_provider_id bigint not null,
  constraint cc_stock_products_pkey primary key (id),
  constraint cc_stock_products_cc_stock_product_category_id_fkey foreign KEY (cc_stock_product_category_id) references cc_stock_product_categories (id),
  constraint cc_stock_products_cc_stock_product_measure_unit_id_fkey foreign KEY (cc_stock_product_measure_unit_id) references cc_stock_product_measure_units (id),
  constraint cc_stock_products_cc_stock_provider_id_fkey foreign KEY (cc_stock_provider_id) references cc_stock_providers (id) on update CASCADE on delete CASCADE,
  constraint cc_stock_products_cc_user_business_id_fkey foreign KEY (cc_user_business_id) references cc_user_businesses (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;
